### ISSUE TITLE
No need to build examples in kr_common

### ISSUE THREAD

**Issue by kartikmohta** [KumarRobotics/kr_utils#6]
In `kr_common`, the examples in the `test` folder are built by default, I think they can be put in an `examples` folder instead and not built by default. I believe `kr_common` should be a header-only package.

**Comment by versatran01** [comment]
Agree. You could just fix it.

**Comment by kartikmohta** [comment]
Fixed in 7def1d3626496a9717b0c44a1ac9b267d9a81646
